# This script should test compilation of conky and conky-all
# xcode 9.4 and xcode 10.1

language: c
matrix:
    include:
    - os: osx
      osx_image: xcode9.4
      script:
        - brew install conky

    - os: osx
      osx_image: xcode9.4
      script:
        - brew install conky-all
      
    - os: osx
      osx_image: xcode10.2
      script:
        - brew install conky

    - os: osx
      osx_image: xcode10.2
      script:
        - brew install conky-all      

before_install:
# install our homebrew tap
  - brew tap Conky-for-macOS/homebrew-formulae

script:
# test build (avoid TravisCI failing for no reason.)
  - echo "int main() {return 0;}" > temp.c
  - gcc temp.c -o temp