language: c
os: osx
osx_image: xcode9.4

before_install:
# install dependancies
  - brew tap Conky-for-macOS/homebrew-formulae
  - brew install conky

script:
# test build (avoid TravisCI failing for no reason.)
  - echo "int main() {return 0;}" > temp.c
  - gcc temp.c -o temp
